chore(project): renaming
SpoonX/aurelia-config pull request #6
Opened 2016-09-15 08:28 UTC by doktordirk

2016-09-15 09:04 UTC, RWOverdijk commented on README.md
> +At aurelia configuration you tell aurelia-config which plugin config it should load and the app config objects you want to merge into that sequentially. Then it (optionally) calls sequentially the pl
Slightly change the readme. I've written a tiny part to show you what I mean: https://gist.github.com/RWOverdijk/b3a5e875e65d70a05a9788c8774b2e05

2016-09-15 09:04 UTC, RWOverdijk commented on config.js
> +    "extend": "npm:extend@3.0.0",
Remove, not needed

2016-09-15 09:04 UTC, RWOverdijk commented on package.json
> +      "extend": "^3.0.0"
Not needed

2016-09-15 09:05 UTC, RWOverdijk commented on src/aurelia-config.js
>    frameworkConfiguration.container.registerInstance(ConfigManager, configManager);
Newline between statements and assignments.

2016-09-15 09:06 UTC, RWOverdijk commented on src/aurelia-config.js
> +  return configManager.mergeConfigsSynchronous(plugins.concat(appConfigs))
```js
return configManager.mergeDefaultsSynchronous(plugins.concat(appConfigs)).then(() => {
  if (config.fetch('aurelia-config.configure')) {
    configManager.configurePlugins(frameworkConfiguration, plugins.slice());
  }
});
```

2016-09-15 09:06 UTC, RWOverdijk requested changes
Reviewed. Mostly looks good, but I have some minor feedback.

2016-09-15 09:06 UTC, RWOverdijk commented on test/aurelia-config.spec.js
> +import extend from 'extend';
You don't need `extend`, we have Homefront which exposes a `static .merge()`.

2016-09-20 12:37 UTC, doktordirk commented
@RWOverdijk all new and shiny

2016-09-20 12:42 UTC, RWOverdijk commented
I like shiny. I'll review this asap :)

2016-09-20 12:44 UTC, doktordirk commented on test/aurelia-config.spec.js
> +import extend from 'extend';
done

2016-09-20 12:45 UTC, doktordirk commented on README.md
> +At aurelia configuration you tell aurelia-config which plugin config it should load and the app config objects you want to merge into that sequentially. Then it (optionally) calls sequentially the pl
done

2016-09-20 12:45 UTC, doktordirk commented on config.js
> +    "extend": "npm:extend@3.0.0",
done

2016-09-20 12:45 UTC, doktordirk commented on src/aurelia-config.js
>    frameworkConfiguration.container.registerInstance(ConfigManager, configManager);
obsolete/done

2016-09-20 12:46 UTC, doktordirk commented on src/aurelia-config.js
> +  return configManager.mergeConfigsSynchronous(plugins.concat(appConfigs))
obsolete

2016-09-28 08:52 UTC, RWOverdijk approved these changes
Did the review two days ago, but I forgot to approve. My bad.

2016-09-28 09:38 UTC, doktordirk commented
@RWOverdijk uff :) so please merge (and/or put the repo on sx-elite so i can do it)

2016-10-02 09:27 UTC, merged